version: '3'

tasks:
  lint:
    description: Lint the code
    cmds:
    - uv run mypy ./django_rls
  test:
    description: Run tests
    dir: "./tests"
    cmds:
      - cd testproject && uv run  migrate.py
      - uv run pytest --ds=tests.testproject.settings --cov=django_rls --cov-report=xml


  serve:
    description: Serve the documentation
    cmds:
      - uv run docs/pre_build.py
      - uv run mkdocs serve

  deploy_docs:
    description: Deploy the documentation
    cmds:
      - uv run docs/pre_build.py
      - uv run mkdocs build
      - uv run mkdocs gh-deploy