# Generated by Django 5.2.8 on 2025-12-03 15:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MixedModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.RunSQL(
            sql='DROP POLICY IF EXISTS "test_app_mixedmodel_rls_policy" ON "test_app_mixedmodel";\nCREATE POLICY "test_app_mixedmodel_rls_policy" ON "test_app_mixedmodel" FOR ALL USING ((\n            CASE\n                WHEN current_setting(\'rls.tenant_id\', true) IS NULL THEN FALSE\n                WHEN current_setting(\'rls.tenant_id\') = \'\' THEN FALSE\n                WHEN current_setting(\'rls.tenant_id\') = \'SPECIAL_CASE_NONE\' THEN FALSE\n                WHEN current_setting(\'rls.tenant_id\') = \'SPECIAL_CASE_ALL\' THEN TRUE\n                ELSE tenant_id = current_setting(\'rls.tenant_id\')::int\n            END\n        ) AND\n(\n            CASE\n                WHEN current_setting(\'rls.user_id\', true) IS NULL THEN FALSE\n                WHEN current_setting(\'rls.user_id\') = \'\' THEN FALSE\n                WHEN current_setting(\'rls.user_id\') = \'SPECIAL_CASE_NONE\' THEN FALSE\n                WHEN current_setting(\'rls.user_id\') = \'SPECIAL_CASE_ALL\' THEN TRUE\n                ELSE user_id = current_setting(\'rls.user_id\')::int\n            END\n        )) WITH CHECK ((\n            CASE\n                WHEN current_setting(\'rls.tenant_id\', true) IS NULL THEN FALSE\n                WHEN current_setting(\'rls.tenant_id\') = \'\' THEN FALSE\n                WHEN current_setting(\'rls.tenant_id\') = \'SPECIAL_CASE_NONE\' THEN FALSE\n                WHEN current_setting(\'rls.tenant_id\') = \'SPECIAL_CASE_ALL\' THEN TRUE\n                ELSE tenant_id = current_setting(\'rls.tenant_id\')::int\n            END\n        ) AND\n(\n            CASE\n                WHEN current_setting(\'rls.user_id\', true) IS NULL THEN FALSE\n                WHEN current_setting(\'rls.user_id\') = \'\' THEN FALSE\n                WHEN current_setting(\'rls.user_id\') = \'SPECIAL_CASE_NONE\' THEN FALSE\n                WHEN current_setting(\'rls.user_id\') = \'SPECIAL_CASE_ALL\' THEN TRUE\n                ELSE user_id = current_setting(\'rls.user_id\')::int\n            END\n        ));\nALTER TABLE "test_app_mixedmodel" ENABLE ROW LEVEL SECURITY;\nALTER TABLE "test_app_mixedmodel" FORCE ROW LEVEL SECURITY;',
            reverse_sql='ALTER TABLE "test_app_mixedmodel" NO FORCE ROW LEVEL SECURITY;\nALTER TABLE "test_app_mixedmodel" DISABLE ROW LEVEL SECURITY;\nDROP POLICY IF EXISTS "test_app_mixedmodel_rls_policy" ON "test_app_mixedmodel";',
        ),
        migrations.CreateModel(
            name='NoRLSModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TenantModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tenant_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RunSQL(
            sql='DROP POLICY IF EXISTS "test_app_tenantmodel_rls_policy" ON "test_app_tenantmodel";\nCREATE POLICY "test_app_tenantmodel_rls_policy" ON "test_app_tenantmodel" FOR ALL USING ((\n            CASE\n                WHEN current_setting(\'rls.tenant_id\', true) IS NULL THEN FALSE\n                WHEN current_setting(\'rls.tenant_id\') = \'\' THEN FALSE\n                WHEN current_setting(\'rls.tenant_id\') = \'SPECIAL_CASE_NONE\' THEN FALSE\n                WHEN current_setting(\'rls.tenant_id\') = \'SPECIAL_CASE_ALL\' THEN TRUE\n                ELSE tenant_id = current_setting(\'rls.tenant_id\')::int\n            END\n        )) WITH CHECK ((\n            CASE\n                WHEN current_setting(\'rls.tenant_id\', true) IS NULL THEN FALSE\n                WHEN current_setting(\'rls.tenant_id\') = \'\' THEN FALSE\n                WHEN current_setting(\'rls.tenant_id\') = \'SPECIAL_CASE_NONE\' THEN FALSE\n                WHEN current_setting(\'rls.tenant_id\') = \'SPECIAL_CASE_ALL\' THEN TRUE\n                ELSE tenant_id = current_setting(\'rls.tenant_id\')::int\n            END\n        ));\nALTER TABLE "test_app_tenantmodel" ENABLE ROW LEVEL SECURITY;\nALTER TABLE "test_app_tenantmodel" FORCE ROW LEVEL SECURITY;',
            reverse_sql='ALTER TABLE "test_app_tenantmodel" NO FORCE ROW LEVEL SECURITY;\nALTER TABLE "test_app_tenantmodel" DISABLE ROW LEVEL SECURITY;\nDROP POLICY IF EXISTS "test_app_tenantmodel_rls_policy" ON "test_app_tenantmodel";',
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.RunSQL(
            sql='DROP POLICY IF EXISTS "test_app_usermodel_rls_policy" ON "test_app_usermodel";\nCREATE POLICY "test_app_usermodel_rls_policy" ON "test_app_usermodel" FOR ALL USING ((\n            CASE\n                WHEN current_setting(\'rls.user_id\', true) IS NULL THEN FALSE\n                WHEN current_setting(\'rls.user_id\') = \'\' THEN FALSE\n                WHEN current_setting(\'rls.user_id\') = \'SPECIAL_CASE_NONE\' THEN FALSE\n                WHEN current_setting(\'rls.user_id\') = \'SPECIAL_CASE_ALL\' THEN TRUE\n                ELSE user_id = current_setting(\'rls.user_id\')::int\n            END\n        )) WITH CHECK ((\n            CASE\n                WHEN current_setting(\'rls.user_id\', true) IS NULL THEN FALSE\n                WHEN current_setting(\'rls.user_id\') = \'\' THEN FALSE\n                WHEN current_setting(\'rls.user_id\') = \'SPECIAL_CASE_NONE\' THEN FALSE\n                WHEN current_setting(\'rls.user_id\') = \'SPECIAL_CASE_ALL\' THEN TRUE\n                ELSE user_id = current_setting(\'rls.user_id\')::int\n            END\n        ));\nALTER TABLE "test_app_usermodel" ENABLE ROW LEVEL SECURITY;\nALTER TABLE "test_app_usermodel" FORCE ROW LEVEL SECURITY;',
            reverse_sql='ALTER TABLE "test_app_usermodel" NO FORCE ROW LEVEL SECURITY;\nALTER TABLE "test_app_usermodel" DISABLE ROW LEVEL SECURITY;\nDROP POLICY IF EXISTS "test_app_usermodel_rls_policy" ON "test_app_usermodel";',
        ),
        migrations.CreateModel(
            name='UUIDMixedModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField()),
                ('user_id', models.UUIDField()),
                ('content', models.TextField()),
            ],
        ),
        migrations.RunSQL(
            sql='DROP POLICY IF EXISTS "test_app_uuidmixedmodel_rls_policy" ON "test_app_uuidmixedmodel";\nCREATE POLICY "test_app_uuidmixedmodel_rls_policy" ON "test_app_uuidmixedmodel" FOR ALL USING ((\n            CASE\n                WHEN current_setting(\'rls.tenant_id\', true) IS NULL THEN FALSE\n                WHEN current_setting(\'rls.tenant_id\') = \'\' THEN FALSE\n                WHEN current_setting(\'rls.tenant_id\') = \'SPECIAL_CASE_NONE\' THEN FALSE\n                WHEN current_setting(\'rls.tenant_id\') = \'SPECIAL_CASE_ALL\' THEN TRUE\n                ELSE tenant_id = current_setting(\'rls.tenant_id\')::uuid\n            END\n        ) AND\n(\n            CASE\n                WHEN current_setting(\'rls.user_id\', true) IS NULL THEN FALSE\n                WHEN current_setting(\'rls.user_id\') = \'\' THEN FALSE\n                WHEN current_setting(\'rls.user_id\') = \'SPECIAL_CASE_NONE\' THEN FALSE\n                WHEN current_setting(\'rls.user_id\') = \'SPECIAL_CASE_ALL\' THEN TRUE\n                ELSE user_id = current_setting(\'rls.user_id\')::uuid\n            END\n        )) WITH CHECK ((\n            CASE\n                WHEN current_setting(\'rls.tenant_id\', true) IS NULL THEN FALSE\n                WHEN current_setting(\'rls.tenant_id\') = \'\' THEN FALSE\n                WHEN current_setting(\'rls.tenant_id\') = \'SPECIAL_CASE_NONE\' THEN FALSE\n                WHEN current_setting(\'rls.tenant_id\') = \'SPECIAL_CASE_ALL\' THEN TRUE\n                ELSE tenant_id = current_setting(\'rls.tenant_id\')::uuid\n            END\n        ) AND\n(\n            CASE\n                WHEN current_setting(\'rls.user_id\', true) IS NULL THEN FALSE\n                WHEN current_setting(\'rls.user_id\') = \'\' THEN FALSE\n                WHEN current_setting(\'rls.user_id\') = \'SPECIAL_CASE_NONE\' THEN FALSE\n                WHEN current_setting(\'rls.user_id\') = \'SPECIAL_CASE_ALL\' THEN TRUE\n                ELSE user_id = current_setting(\'rls.user_id\')::uuid\n            END\n        ));\nALTER TABLE "test_app_uuidmixedmodel" ENABLE ROW LEVEL SECURITY;\nALTER TABLE "test_app_uuidmixedmodel" FORCE ROW LEVEL SECURITY;',
            reverse_sql='ALTER TABLE "test_app_uuidmixedmodel" NO FORCE ROW LEVEL SECURITY;\nALTER TABLE "test_app_uuidmixedmodel" DISABLE ROW LEVEL SECURITY;\nDROP POLICY IF EXISTS "test_app_uuidmixedmodel_rls_policy" ON "test_app_uuidmixedmodel";',
        ),
        migrations.CreateModel(
            name='UUIDTenantModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tenant_id', models.UUIDField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RunSQL(
            sql='DROP POLICY IF EXISTS "test_app_uuidtenantmodel_rls_policy" ON "test_app_uuidtenantmodel";\nCREATE POLICY "test_app_uuidtenantmodel_rls_policy" ON "test_app_uuidtenantmodel" FOR ALL USING ((\n            CASE\n                WHEN current_setting(\'rls.tenant_id\', true) IS NULL THEN FALSE\n                WHEN current_setting(\'rls.tenant_id\') = \'\' THEN FALSE\n                WHEN current_setting(\'rls.tenant_id\') = \'SPECIAL_CASE_NONE\' THEN FALSE\n                WHEN current_setting(\'rls.tenant_id\') = \'SPECIAL_CASE_ALL\' THEN TRUE\n                ELSE tenant_id = current_setting(\'rls.tenant_id\')::uuid\n            END\n        )) WITH CHECK ((\n            CASE\n                WHEN current_setting(\'rls.tenant_id\', true) IS NULL THEN FALSE\n                WHEN current_setting(\'rls.tenant_id\') = \'\' THEN FALSE\n                WHEN current_setting(\'rls.tenant_id\') = \'SPECIAL_CASE_NONE\' THEN FALSE\n                WHEN current_setting(\'rls.tenant_id\') = \'SPECIAL_CASE_ALL\' THEN TRUE\n                ELSE tenant_id = current_setting(\'rls.tenant_id\')::uuid\n            END\n        ));\nALTER TABLE "test_app_uuidtenantmodel" ENABLE ROW LEVEL SECURITY;\nALTER TABLE "test_app_uuidtenantmodel" FORCE ROW LEVEL SECURITY;',
            reverse_sql='ALTER TABLE "test_app_uuidtenantmodel" NO FORCE ROW LEVEL SECURITY;\nALTER TABLE "test_app_uuidtenantmodel" DISABLE ROW LEVEL SECURITY;\nDROP POLICY IF EXISTS "test_app_uuidtenantmodel_rls_policy" ON "test_app_uuidtenantmodel";',
        ),
    ]
