from django.db.migrations.operations.base import Operation


class RunDynamicSQL(Operation):
    """
    A custom migration operation that generates SQL at runtime.
    
    This operation is used to create and drop RLS policies dynamically.
    The SQL is generated by the provided functions at migration time,
    allowing for dynamic table and policy name resolution.
    
    Args:
        create_func: A callable that takes a schema_editor and returns SQL string
                     to create the RLS policy.
        drop_func: A callable that takes a schema_editor and returns SQL string
                   to drop the RLS policy.
    """

    reversible = True

    def __init__(self, create_func, drop_func):
        self.create_func = create_func
        self.drop_func = drop_func

    def state_forwards(self, app_label, state):
        # This operation doesn't affect the state.
        pass

    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        sql = self.create_func(schema_editor)
        # Execute each statement separately
        # Split by newline first, then filter out empty lines
        # Each line should be a complete SQL statement ending with semicolon
        statements = [s.strip() for s in sql.split('\n') if s.strip() and not s.strip().startswith('--')]
        for statement in statements:
            if statement:
                schema_editor.execute(statement)

    def database_backwards(self, app_label, schema_editor, from_state, to_state):
        sql = self.drop_func(schema_editor)
        # Execute each statement separately
        # Split by newline first, then filter out empty lines
        statements = [s.strip() for s in sql.split('\n') if s.strip() and not s.strip().startswith('--')]
        for statement in statements:
            if statement:
                schema_editor.execute(statement)

    def describe(self):
        return "Run dynamic SQL for RLS policy"

    def deconstruct(self):
        # Provide enough information so that the migration can be serialized.
        return (
            self.__class__.__name__,
            [],
            {'create_func': self.create_func, 'drop_func': self.drop_func},
        )

